// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.lu
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnRR1COI86cG2PmbgkDW35Zt4Y4NIntco',
    appId: '1:1007522151015:web:3c216b5d1fde07ad7ff2c2',
    messagingSenderId: '1007522151015',
    projectId: 'chatapp-803a7',
    authDomain: 'chatapp-803a7.firebaseapp.com',
    storageBucket: 'chatapp-803a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Miwfjf8jV3gneHMI6yQCQv2qi6xMI9E',
    appId: '1:1007522151015:android:0ff8428cdee61eb37ff2c2',
    messagingSenderId: '1007522151015',
    projectId: 'chatapp-803a7',
    storageBucket: 'chatapp-803a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHLfQScG7trTDYCo4vvC4_l_UNoo3vyxE',
    appId: '1:1007522151015:ios:1609171dad8f233e7ff2c2',
    messagingSenderId: '1007522151015',
    projectId: 'chatapp-803a7',
    storageBucket: 'chatapp-803a7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHLfQScG7trTDYCo4vvC4_l_UNoo3vyxE',
    appId: '1:1007522151015:ios:1609171dad8f233e7ff2c2',
    messagingSenderId: '1007522151015',
    projectId: 'chatapp-803a7',
    storageBucket: 'chatapp-803a7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnRR1COI86cG2PmbgkDW35Zt4Y4NIntco',
    appId: '1:1007522151015:web:7fdba6bccc328b9a7ff2c2',
    messagingSenderId: '1007522151015',
    projectId: 'chatapp-803a7',
    authDomain: 'chatapp-803a7.firebaseapp.com',
    storageBucket: 'chatapp-803a7.appspot.com',
  );

}